#! /bin/bash
#
#    LogSplitter.sh START/STOP script
# chkconfig: 2345 90 60
# description: LogSplitting Script


#Source function library
. /etc/init.d/functions


prog="LogSplitter"
path_to_script="/WideSpan/mon/LogSplitter.pl"
logfile_to_read="/var/log/messages"
config="/WideSpan/mon/SplitConfig.cfg"

start() {
        process_run=`ps -ef |grep LogSplitter | grep -v grep | wc -l`
        echo "Starting $prog: "
        if [ -e $path_to_script -a $process_run == 0 ]; then
              exec $path_to_script $logfile_to_read $config&
        else
               echo -n "Logging Script does not exist or process is already running"
        fi
}

stop() {
        process_run=`ps -ef |grep LogSplitter | grep -v grep | wc -l`
        echo "Stopping $prog: "
        if [ $process_run == 0 ]; then
            echo "cannot stop LogSplitter: Script is not running."
            exit 1
        fi
        killproc -p /tmp/LogSplitter.pid
        return 0
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit $?

